### ISSUE TITLE
Update the card section file in components folder

### ISSUE THREAD

**Issue by Aishika3** [Aishika3/Time-Tracker-VS-Code-extension-Tracker#2]

**Comment by CS-parth** [comment]
Can this issue be assigned!
Also, can you give me more detail about the card section

**Comment by Aishika3** [comment]
For the design part, you can check it out:-https://bootcamp.uxdesign.cc/4-popular-types-of-cards-in-ui-design-c805406ea0f3
First, you have to make the Figma and Canva design and write the react code in the index.jsx(src->components->card), and write its respective css to it. This card component will be used in other parts of the project and there we just have to import it and use it directly and do not have to write the same piece of code again.

**Comment by Aishika3** [comment]
For more information please communicate through discord by tagging me
