### ISSUE TITLE
Design and create a login and registration page.

### ISSUE THREAD

**Issue by Aishika3** [Aishika3/Time-Tracker-VS-Code-extension-Tracker#5]
You can refer the the image below:-
![Register](https://github.com/Aishika3/Time-Tracker-VS-Code-extension-Tracker/assets/96141359/bb655262-937e-42f6-baf4-03189d078ff0)
![Login](https://github.com/Aishika3/Time-Tracker-VS-Code-extension-Tracker/assets/96141359/7daafd50-047b-4b98-9193-b4b6bbab0fa8)

**Comment by Aishika3** [comment]
Design,ceate and develop the two pages in src->projects-> Login component.There write the needed code for jsx and css file

**Comment by VanshVg** [comment]
Can I work on this issue?

**Comment by Aishika3** [comment]
Yeah for any doubts contact me through the discord

**Comment by Aishika3** [comment]
Yeah contact me through discord by tagging me for further doubts

**Comment by VanshVg** [comment]
May i ask your discord id?

**Comment by Aishika3** [comment]
Link to the discord of csoc:-https://discord.gg/JnJcU6Ht
You must go to the time-tracker-extension part of that discord and tag there for further doubts.
