### ISSUE TITLE
Updated the navbar section in the component folder

### ISSUE THREAD

**Issue by Aishika3** [Aishika3/Time-Tracker-VS-Code-extension-Tracker#8]
The links in the navbar must contain home page link, project section link,visual representation link,user login page.Leave the links blank will be filled afterwards.

**Comment by sunshinemoua** [comment]
Hi @Aishika3, I'd like to work on this issue. Please let me know if someone is already actively working on this or if it can be assigned to me. I would like to integrate react-router-dom for the links. Thanks!

**Comment by Aishika3** [comment]
Yes please go ahead. For more queries you can communicate through discord

**Comment by sunshinemoua** [comment]
I can't find the Discord channel. Can you add me on Discord? My username is sunshineee. Thanks!!

**Comment by Aishika3** [comment]
Please join from here:-https://discord.gg/JnJcU6Ht

**Comment by Aishika3** [comment]
Yeah go for the styling part
