### ISSUE TITLE
Develop the home or the main page section describing about the details of the project 

### ISSUE THREAD

**Issue by Aishika3** [Aishika3/Time-Tracker-VS-Code-extension-Tracker#9]
First, create a figma or Canva file and show it to me and please take help from the readme file for the description part and also add the necessary images.Path to the home page is src->Projects->Home. Write necessary JSX code and css code.

**Comment by CS-parth** [comment]
Can this issue be assigned!

**Comment by Aishika3** [comment]
For more queries contact through discord.
